services:
  # FastAPI Server
  - type: web
    name: qgr-retrieval-plugin 
    region: oregon
    plan: free
    env: docker
    dockerfilePath: ./Dockerfile
    envVars: 
      - key: DATASTORE
        value: milvus
      - key: BEARER_TOKEN
        generateValue: true 
      - key: MILVUS_HOST
        fromService:
          type: pserv
          name: milvus-service
          property: host
      - key: MILVUS_PORT
        value: 19530
      - key: MILVUS_COLLECTION
        value: QGRmemory
      - key: MILVUS_INDEX_PARAMS
        value: '{"metric_type": "IP", "index_type": "IVF_FLAT", "params": {"nlist": 2048}}'
      - key: MILVUS_SEARCH_PARAMS
        value: '{"metric_type": "IP", "param": {"nprobe": 1000}, "round_decimal": -1}'
